import type { ThemeDefinition } from 'vuetify';

export interface AppTheme {
  id: string;
  name: string;
  description: string;
  light: ThemeDefinition;
  dark: ThemeDefinition;
  /** If true, this theme only has a dark variant (light mode will be disabled) */
  darkOnly?: boolean;
}

export const themes: AppTheme[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Modern orange accent theme',
    light: {
      dark: false,
      colors: {
        primary: '#E55A2B',
        secondary: '#1E3A5F',
        accent: '#D4A84B',
        error: '#D93251',
        info: '#0D7A9E',
        success: '#059669',
        warning: '#D97706',
        background: '#F1F5F9',
        surface: '#FFFFFF',
        'surface-variant': '#E2E8F0',
        'surface-bright': '#FFFFFF',
        'on-background': '#1E293B',
        'on-surface': '#1E293B',
        'on-surface-variant': '#475569',
      },
    },
    dark: {
      dark: true,
      colors: {
        primary: '#FF8C42',
        secondary: '#2E4A6F',
        accent: '#FFD166',
        error: '#EF476F',
        info: '#118AB2',
        success: '#06D6A0',
        warning: '#FFD166',
        background: '#121212',
        surface: '#1E1E1E',
        'surface-variant': '#2D2D2D',
        'on-background': '#E0E0E0',
        'on-surface': '#E0E0E0',
      },
    },
  },
  {
    id: 'firefly',
    name: 'Firefly III',
    description: 'Classic Firefly III blue theme',
    light: {
      dark: false,
      colors: {
        primary: '#3C8DBC',
        secondary: '#00A65A',
        accent: '#F39C12',
        error: '#DD4B39',
        info: '#00C0EF',
        success: '#00A65A',
        warning: '#F39C12',
        background: '#ECF0F5',
        surface: '#FFFFFF',
        'surface-variant': '#D2D6DE',
        'surface-bright': '#FFFFFF',
        'on-background': '#1F2D3D',
        'on-surface': '#1F2D3D',
        'on-surface-variant': '#6C757D',
      },
    },
    dark: {
      dark: true,
      colors: {
        primary: '#067240',
        secondary: '#5998BE',
        accent: '#f39c12',
        error: '#d73925',
        info: '#41CDE0',
        success: '#00A65A',
        warning: '#f39c12',
        background: '#353C42',
        surface: '#272C30',
        'surface-variant': '#2C3B41',
        'surface-bright': '#374850',
        'on-background': '#B8C7CE',
        'on-surface': '#B8C7CE',
        'on-surface-variant': '#8AA4AF',
      },
    },
  },
  {
    id: 'solarized',
    name: 'Solarized',
    description: "Ethan Schoonover's precision colors",
    light: {
      dark: false,
      colors: {
        primary: '#268BD2',
        secondary: '#2AA198',
        accent: '#B58900',
        error: '#DC322F',
        info: '#268BD2',
        success: '#859900',
        warning: '#CB4B16',
        background: '#FDF6E3',
        surface: '#EEE8D5',
        'surface-variant': '#DDD6C3',
        'surface-bright': '#FDF6E3',
        'on-background': '#657B83',
        'on-surface': '#586E75',
        'on-surface-variant': '#839496',
      },
    },
    dark: {
      dark: true,
      colors: {
        primary: '#268BD2',
        secondary: '#2AA198',
        accent: '#B58900',
        error: '#DC322F',
        info: '#268BD2',
        success: '#859900',
        warning: '#CB4B16',
        background: '#002B36',
        surface: '#073642',
        'surface-variant': '#094352',
        'on-background': '#839496',
        'on-surface': '#93A1A1',
      },
    },
  },
  {
    id: 'one',
    name: 'One',
    description: 'Atom editor inspired theme',
    light: {
      dark: false,
      colors: {
        primary: '#4078F2',
        secondary: '#50A14F',
        accent: '#986801',
        error: '#E45649',
        info: '#0184BC',
        success: '#50A14F',
        warning: '#C18401',
        background: '#FAFAFA',
        surface: '#FFFFFF',
        'surface-variant': '#EAEAEB',
        'surface-bright': '#FFFFFF',
        'on-background': '#383A42',
        'on-surface': '#383A42',
        'on-surface-variant': '#696C77',
      },
    },
    dark: {
      dark: true,
      colors: {
        primary: '#61AFEF',
        secondary: '#98C379',
        accent: '#E5C07B',
        error: '#E06C75',
        info: '#56B6C2',
        success: '#98C379',
        warning: '#D19A66',
        background: '#282C34',
        surface: '#21252B',
        'surface-variant': '#2C323C',
        'on-background': '#ABB2BF',
        'on-surface': '#ABB2BF',
      },
    },
  },
  {
    id: 'synthwave',
    name: "Synthwave '84",
    description: 'Retro-futuristic neon theme',
    darkOnly: true,
    light: {
      dark: false,
      colors: {
        primary: '#FF7EDB',
        secondary: '#36F9F6',
        accent: '#FEDE5D',
        error: '#FE4450',
        info: '#36F9F6',
        success: '#72F1B8',
        warning: '#F97E72',
        background: '#241B2F',
        surface: '#262335',
        'surface-variant': '#34294F',
        'surface-bright': '#2A2139',
        'on-background': '#FFFFFF',
        'on-surface': '#FFFFFF',
        'on-surface-variant': '#848BBD',
      },
    },
    dark: {
      dark: true,
      colors: {
        primary: '#FF7EDB',
        secondary: '#36F9F6',
        accent: '#FEDE5D',
        error: '#FE4450',
        info: '#36F9F6',
        success: '#72F1B8',
        warning: '#F97E72',
        background: '#262335',
        surface: '#241B2F',
        'surface-variant': '#34294F',
        'on-background': '#FFFFFF',
        'on-surface': '#FFFFFF',
      },
    },
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin',
    description: 'Soothing pastel theme (Latte/Mocha)',
    light: {
      dark: false,
      colors: {
        primary: '#1E66F5',
        secondary: '#179299',
        accent: '#DF8E1D',
        error: '#D20F39',
        info: '#04A5E5',
        success: '#40A02B',
        warning: '#FE640B',
        background: '#EFF1F5',
        surface: '#CCD0DA',
        'surface-variant': '#BCC0CC',
        'surface-bright': '#EFF1F5',
        'on-background': '#4C4F69',
        'on-surface': '#4C4F69',
        'on-surface-variant': '#5C5F77',
      },
    },
    dark: {
      dark: true,
      colors: {
        primary: '#89B4FA',
        secondary: '#94E2D5',
        accent: '#F9E2AF',
        error: '#F38BA8',
        info: '#89DCEB',
        success: '#A6E3A1',
        warning: '#FAB387',
        background: '#1E1E2E',
        surface: '#313244',
        'surface-variant': '#45475A',
        'on-background': '#CDD6F4',
        'on-surface': '#CDD6F4',
      },
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    description: 'Dark theme with vibrant colors',
    light: {
      dark: false,
      colors: {
        primary: '#9B6BDF',
        secondary: '#1EF1C6',
        accent: '#FFCA80',
        error: '#F37878',
        info: '#80BFFF',
        success: '#70F1A1',
        warning: '#FFCA80',
        background: '#F8F8F2',
        surface: '#FFFFFF',
        'surface-variant': '#E8E8E2',
        'surface-bright': '#FFFFFF',
        'on-background': '#282A36',
        'on-surface': '#282A36',
        'on-surface-variant': '#44475A',
      },
    },
    dark: {
      dark: true,
      colors: {
        primary: '#BD93F9',
        secondary: '#50FA7B',
        accent: '#F1FA8C',
        error: '#FF5555',
        info: '#8BE9FD',
        success: '#50FA7B',
        warning: '#FFB86C',
        background: '#282A36',
        surface: '#44475A',
        'surface-variant': '#6272A4',
        'on-background': '#F8F8F2',
        'on-surface': '#F8F8F2',
      },
    },
  },
];

export const defaultThemeId = 'default';

export function getThemeById(id: string): AppTheme | undefined {
  return themes.find((t) => t.id === id);
}

export function getVuetifyThemeName(themeId: string, isDark: boolean): string {
  return `${themeId}-${isDark ? 'dark' : 'light'}`;
}
