name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of FireflyIII Toolbox are you using?
      placeholder: e.g., 1.0.0 or commit hash
    validations:
      required: false

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running FireflyIII Toolbox?
      options:
        - Docker
        - Docker Compose
        - Node.js (npm run dev)
        - Node.js (npm run build + production)
        - Other
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Any relevant environment details (browser, OS, FireflyIII version, etc.)
      placeholder: |
        - Browser: Chrome 120
        - OS: Windows 11
        - FireflyIII: v6.1.0
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant log output or error messages. This will be automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the problem here.
    validations:
      required: false
